# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title
#' freq_value
#' @description
#' This function determines the most frequently occurring value in an integer
#' vector (mode). If the mode is ambiguous, a function returns any mode.
#' @details
#' ARGUMENTS:
#' x - a integer vector
#'
#' RETURN VALUE:
#' a integer value
#'
#' @family fungroup
#' @export
freq_value <- function(x) {
    .Call('mypackage_freq_value', PACKAGE = 'mypackage', x)
}

#' @title
#' list2array
#' @description
#' If a given list (of length l >= 0) of numeric vectors has all vectors of the
#' same length k >= 0 this function returns a numeric matrix (k, l):
#' each column of the matrix corresponds to one element from the list.
#' If lengths of vectors in given list are not the same, a function returns
#' this list.
#' @details
#' ARGUMENTS:
#' x - a list (of length l >= 0) of numeric vectors
#'
#' RETURN VALUE:
#' a matrix or a list
#'
#' @family fungroup
#' @export
list2array <- function(x) {
    .Call('mypackage_list2array', PACKAGE = 'mypackage', x)
}

#' @title
#' perms
#' @description
#' This function generates all the possible permutations of the set
#' {1, 2, ..., n} (for some given n). A function removes missing values.
#' @details
#' ARGUMENTS:
#' x - a integer vector
#'
#' RETURN VALUE:
#' a matrix with n! rows and n columns
#'
#' @family fungroup
#' @export
perms <- function(x) {
    .Call('mypackage_perms', PACKAGE = 'mypackage', x)
}

